apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kiteworks-app
  namespace: kiteworks-prod
spec:
  ingressClassName: nginx
  rules:
    - host: kiteworkstest-prod.centralus.cloudapp.azure.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kiteworks-app
                port:
                  number: 80